### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by drSun** [TonisOrmisson/yii-usuario-views-bootstrap4#1]
Hi, thanks for the repo!
Is there a real need of php version > 8? Can't install this theme on old projects with php 7.4. What critical can be there in simple views which needs php8? Thanks.

**Comment by TonisOrmisson** [comment]
ok, [c8c5443](https://github.com/TonisOrmisson/yii-usuario-views-bootstrap4/commit/c8c54433703f649f3e5ef44c3f16f299e2687f06)

**Comment by drSun** [comment]
Thank you, you are the best.
